In [1]:
using JuMP
using Gurobi
using DataFrames
using CSV
using LinearAlgebra
using Plots
using Statistics

In [50]:
A = zeros(18,15+11+55+18);
C = zeros(15+11+55+18)

99-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [51]:
#Shifts of 4h
for j=1:14
    A[j:j+3,j].+=1
    C[j] = 25*4
end

#Shifts of 8h
for j=1:10
    A[j:j+7,j+15].+=1
    C[j+15] = 20*8
end

#Shifts of 1h
for j=1:18
    A[j,j+15+11]+=1
    C[j+15+11] = 40
end

#Overtime Shifts
n = 0
for k=9:18
    for j=1:(18-k+1)
        A[j:j+k-1,j+15+11+18+n].+=1
        if k<11
            C[j+15+11+18+n] = 20*8+30*(k-8)
        else
            C[j+15+11+18+n] = 20*8+30*2+35*(k-10)
        end
    end
    n+=(18-k+1)
end

In [133]:
D1 = convert(Matrix,CSV.File("HW2_demand.csv"; header=true) |> DataFrame!)[:,2:73];
D = D1[:,1:4:72]

35×18 Array{Any,2}:
  4  29  72   54   80  26  15  40   87  47  31  34   35  77  36  51  27   4
  7  21  50  118   62  54  27  77   45  42  46  73   53  86  45  37  26  19
 24   4  35   51   93  36  15  67   84  37  45  54   51  78  71  53  26  13
 12  19  38   76   47  21   6  62   48  44  38  19   43  55  70  40  39  13
 11   6  46   70  109  34  20  51   62  59  15  46   49  51  46  40  44  23
  8  15  54  109   53  35  28  51   69  66  32  48   52  60  38  40  11   6
  7  14  33   60   41  23  24  46   68  21  56  53   40  91  63  35  29  18
 11   9  64   29   53  44  23  40   52  32  43  64   43  57  28  47  20  16
  4  11  51  103   39  30  26  48   86  54  29  59   68  66  69  80  41  23
  4  14  49   66   41  29  29  55   43  66  22  48   76  89  44  63  40  12
  4   4  44   62   65  34  23  77  125  33  30  46   58  89  56  46  41  12
 17  11  39   70   61  36  17  63   97  48  18  55   44  60  70  39  37  14
  4   4  52   78   73  24  13  31   76  30  18  75   58  67  45  53 

In [47]:
A

18×99 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  1.0  0.0  0.0  1.0  0.0  1.0
 1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  1.0  1.0  0.0  1.0  1.0  1.0
 1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 

In [52]:
C

99-element Array{Float64,1}:
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
   ⋮
 360.0
 360.0
 395.0
 395.0
 395.0
 395.0
 430.0
 430.0
 430.0
 465.0
 465.0
 500.0

In [72]:
D[:,1:4:72]

35×18 Array{Any,2}:
  4  29  72   54   80  26  15  40   87  47  31  34   35  77  36  51  27   4
  7  21  50  118   62  54  27  77   45  42  46  73   53  86  45  37  26  19
 24   4  35   51   93  36  15  67   84  37  45  54   51  78  71  53  26  13
 12  19  38   76   47  21   6  62   48  44  38  19   43  55  70  40  39  13
 11   6  46   70  109  34  20  51   62  59  15  46   49  51  46  40  44  23
  8  15  54  109   53  35  28  51   69  66  32  48   52  60  38  40  11   6
  7  14  33   60   41  23  24  46   68  21  56  53   40  91  63  35  29  18
 11   9  64   29   53  44  23  40   52  32  43  64   43  57  28  47  20  16
  4  11  51  103   39  30  26  48   86  54  29  59   68  66  69  80  41  23
  4  14  49   66   41  29  29  55   43  66  22  48   76  89  44  63  40  12
  4   4  44   62   65  34  23  77  125  33  30  46   58  89  56  46  41  12
 17  11  39   70   61  36  17  63   97  48  18  55   44  60  70  39  37  14
  4   4  52   78   73  24  13  31   76  30  18  75   58  67  45  53 

35×72 Array{Any,2}:
  4   4   4   4  29  29  29  29  72  …  51  27  27  27  27   4   4   4   4
  7   7   7   7  21  21  21  21  50     37  26  26  26  26  19  19  19  19
 24  24  24  24   4   4   4   4  35     53  26  26  26  26  13  13  13  13
 12  12  12  12  19  19  19  19  38     40  39  39  39  39  13  13  13  13
 11  11  11  11   6   6   6   6  46     40  44  44  44  44  23  23  23  23
  8   8   8   8  15  15  15  15  54  …  40  11  11  11  11   6   6   6   6
  7   7   7   7  14  14  14  14  33     35  29  29  29  29  18  18  18  18
 11  11  11  11   9   9   9   9  64     47  20  20  20  20  16  16  16  16
  4   4   4   4  11  11  11  11  51     80  41  41  41  41  23  23  23  23
  4   4   4   4  14  14  14  14  49     63  40  40  40  40  12  12  12  12
  4   4   4   4   4   4   4   4  44  …  46  41  41  41  41  12  12  12  12
 17  17  17  17  11  11  11  11  39     39  37  37  37  37  14  14  14  14
  4   4   4   4   4   4   4   4  52     53  32  32  32  32   8   8   8   8
  ⋮  

In [144]:
"Build shelter location model 1"
function allocation_1(D, A, C)
    # extract problem dimensions from distance matrix and verify coherence of input data
    T,J  = size(A)
    M = size(D)[1]
    model = Model(Gurobi.Optimizer)
    set_optimizer_attribute(model, "TimeLimit", 30)
    # VARIABLES
    # How many of each shift to use
    @variable(model, x[1:M,1:J] >=0, Int)
    
    #Resource allocation constraint
    @constraint(model, enough_employees[t=1:T, d=1:M],
            sum(A[t, j]*x[d,j]  for j = 1:J) >= D[d, t])
    
    # OBJECTIVE
    @objective(
        model, Min, sum(C[j] * x[d, j] for d=1:M, j=1:J)
    )
    
    optimize!(model)
    
    return model, objective_value(model), x
end

allocation_1

In [146]:
m, o, x = allocation_1(D, A, C)
value.(x)

Academic license - for non-commercial use only - expires 2021-04-27
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (mac64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 18 rows, 99 columns and 814 nonzeros
Model fingerprint: 0x177d10d4
Variable types: 0 continuous, 99 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e+01, 5e+02]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e+00, 2e+01]
Found heuristic solution: objective 12000.000000
Presolve removed 0 rows and 2 columns
Presolve time: 0.00s
Presolved: 18 rows, 97 columns, 814 nonzeros
Variable types: 0 continuous, 97 integer (0 binary)

Root relaxation: objective 4.040000e+03, 15 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0    4040.0000000 4040.00000  0.00%     -   

99-element Array{Float64,1}:
 -0.0
  3.0
  0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
  ⋮
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0

In [143]:
"Build shelter location model 1"
function allocation_2(D, A, C)
    # extract problem dimensions from distance matrix and verify coherence of input data
    T,J  = size(A)
    M = size(D)[1]
    model = Model(Gurobi.Optimizer)
    set_optimizer_attribute(model, "TimeLimit", 30)
    # VARIABLES
    # How many of each shift to use
    @variable(model, x[1:M,1:J] >=0, Int)
    @variable(model, y[1:M, 1:90, 1:J], Bin)
    
    #Resource allocation constraint
    @constraint(model, enough_employees[t=1:T, d=1:M],
            sum(A[t, j]*x[d,j]  for j = 1:J) >= D[d, t])
    
    @constraint(model, limit_fulltime[d=1:M],
            sum(x[d,j]  for j = 16:26) <= 60)
    @constraint(model, limit_parttime[d=1:M],
            sum(x[d,j]  for j = 1:15) <= 30)
    @constraint(model, no_more_two_days[i=1:33, k=1:90],
            sum(y[i,k,j]+y[i+1,k,j]+y[i+2,k,j] for j=1:J) <=2)
    @constraint(model, meet_shift_employees[d=1:M, j=1:J],
            sum(y[d,j]  for j = 1:15) <= 30)
    
    # OBJECTIVE
    @objective(
        model, Min, sum(C[j] * x[d, j] for d=1:M, j=1:J)
    )
    
    optimize!(model)
    
    return model, objective_value(model), x
end

99-element Array{VariableRef,1}:
 x[1]
 x[2]
 x[3]
 x[4]
 x[5]
 x[6]
 x[7]
 x[8]
 x[9]
 x[10]
 x[11]
 x[12]
 x[13]
 ⋮
 x[88]
 x[89]
 x[90]
 x[91]
 x[92]
 x[93]
 x[94]
 x[95]
 x[96]
 x[97]
 x[98]
 x[99]